on: [push]

jobs:
  hello_world_job:
    name: A job to say hello
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Test yuque-action
        uses: Bpazy/yuque-action@master
        with:
          access-token: "this-is-test-access-token"
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
